[mod] Fill the templatespec field with default values
tmax-cloud/template-operator pull request #19
Opened 2021-06-21 02:37 UTC by min-charles

Fill the templatespec(both Template & ClusterTemplate) field with default values

2021-06-21 11:21 UTC, tom721 requested changes

2021-06-21 11:21 UTC, tom721 commented on controllers/clustertemplate_controller.go
> +	//Fill the ClusterTemplateSpec field with default values
함수로 따로 빼서 관리하는 게 가독성이나 이후 관리 차원에서도 더 좋을 것 같아요

2021-06-21 11:21 UTC, tom721 commented on controllers/clustertemplate_controller.go
> +	//Fill the ClusterTemplateSpec field with default values
함수로 따로 빼서 관리하는 게 가독성이나 이후 관리 차원에서도 더 좋을 것 같아요

2021-06-21 11:22 UTC, tom721 commented on controllers/clustertemplate_controller.go
>  	updateInstance := template.DeepCopy()
template을 바꾸고 deepcopy를 떠도 update가 잘되나요?

2021-06-22 05:52 UTC, min-charles commented on controllers/clustertemplate_controller.go
>  	updateInstance := template.DeepCopy()
Yes

2021-06-22 06:05 UTC, min-charles commented on controllers/clustertemplate_controller.go
> +	//Fill the ClusterTemplateSpec field with default values
반영했습니다

2021-06-22 06:07 UTC, tom721 approved these changes

2021-06-22 06:07 UTC, merged